### ISSUE TITLE
Design Data Visualization Formats

### ISSUE THREAD

**Issue by stephane-segning** [ADORSYS-GIS/report-sscrap#26]
- Related #8
- Dependency #25
- Determine the types of charts and graphs that best represent the data (e.g., bar charts, line graphs).
- Design a layout for displaying multiple charts if needed.

**Comment by Arielpetit** [comment]
hey @stephane-segning Please i need some light on a certain aspect on this ticket "Inorder to carry this task in a good and efficient manner, i need to know what kind of data the are to fetch from the different websites" because i don't have a clear view on what data is to be fetch so if you can give me examples of like 5 data examples of those data i will be amazed
